FluuxIO/go-xmpp

client.go
Currently,  when next(c.Session.decoder) produces an error in recv(), the returned error is ignored as recv() is run in a goroutine. This proposed change allows the caller of Recv() to know when recv() has stopped processing packets and act accordingly.
=> Closed receiver chan on error

presence.go
Currently, show, status, and priority are parsed as attributes of a presence stanza. According to section 2.2.2 of the XMPP spec (https://xmpp.org/rfcs/rfc3921.html), these should be child elements of the presence stanza - this pull request aligns this library with the XMPP specification
=> Parse show, status, and priority of presence stanzas as child elements

client.go
Currently, when connecting to the XMPP server, as long as success is false the program will continually try to reconnect. This seems at odds with having a Retry config option in config.go indicating "Number of retries for connect". This pull requests results in a limited amount of retries as specificied by Retry.
=> Fixed infinite retries for failed TCP dial

auth.go, cmd/xmpp-check/xmpp-check.go, cmd/xmpp_jukebox/xmpp_jukebox.go, control_test.go, iot_control.go, iq.go, message.go, message_test.go, msg_chat_markers.go, msg_oob.go, msg_receipts.go, msg_receipts_test.go, pep.go, registry.go, registry_test.go
- Add a registry structure and merge it with IQ Payload registry
- Add support for parsing receipts, chat markers and out of band image urls.
- Clean up the IQPayload interface / marker for IQ payload
=> Add support for parsing message extensions

backoff.go, backoff_test.go, client.go, client_manager.go, cmd/xmpp_echo/xmpp_echo.go, cmd/xmpp_jukebox/xmpp_jukebox.go, config.go, parser.go, session.go
- Support for exponential backoff on reconnect to be gentle on the server.
- Clean up client by moving metrics to the connection managers.
Fixes #21 
Improvements for #8
=> Add Client Manager to monitor connection state and trigger reconnect

_examples/go.mod, _examples/go.sum, _examples/xmpp_component/xmpp_component.go, _examples/xmpp_echo/xmpp_echo.go, _examples/xmpp_jukebox/xmpp_jukebox.go, client.go, client_test.go, component.go, component_test.go, config.go, stream_manager.go
The StreamManager can supervise and handle events for both an XMPP client or an XMPP component.
Fix #38
=> Turn ClientManager into StreamManager

iq_test.go
Take a look here:
https://dev.sum7.eu/genofire/thrempp/-/jobs/1404
---
by the way, why does ProcessOne announce https://github.com/sheenobu/go-xco as xmpp component library ? : https://blog.process-one.net/real-time-stack-issue-23/
=> wrong package import url let it failed

.gitignore, README.md, _examples/delegation/README.md, _examples/delegation/delegation.go, _examples/xmpp_component/README.md, _examples/xmpp_component/xmpp_component.go, _examples/xmpp_echo/xmpp_echo.go, _examples/xmpp_jukebox/xmpp_jukebox.go, auth.go, client.go, client_test.go, component.go, component_test.go, iot_control.go, iq.go, iq_test.go, pep.go, pubsub.go, router.go, router_test.go, stream.go, stream_manager.go
- Add basic support for Router to make it easier to get your code trigger when some packets are received.
- Add initial support for namespace delegation (XEP-0355) and priviledged entities (XEP-0356) and example component.
- Clean up un IQ structures.
=> Add support for initial Router for packet matching & delegation

_examples/delegation/delegation.go, _examples/xmpp_component/xmpp_component.go, _examples/xmpp_echo/xmpp_echo.go, _examples/xmpp_jukebox/xmpp_jukebox.go, client_test.go, component_test.go, iot_control_test.go, iq.go, iq_test.go, router.go, router_test.go, session.go
We thus simplify iq processing.
Here is what the spec says:
"An IQ stanza of type "get" or "set" MUST contain exactly one
child element, which specifies the semantics of the particular
request."
Fixes #50
=> IQ can only have a single payload

router.go, router_test.go
This allows to express route matching on IQ, with a specific namespace and packet type for example.
You can have a different function to handle set, get and error for example.
I also added a test showing that an empty route can act as a catch all matcher.
=> Add StanzaType matcher

_examples/go.mod, _examples/go.sum, client.go, component.go, iq.go, iq_test.go, router.go, router_test.go
We reply with an error not-implemented stanza.
Here is an example stanza error:
```
<iq from="service.localhost" type="error" to="test1@localhost/mremond-mbp" id="1" >
<error type="cancel" code="501" >
<feature-not-implemented xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"/>
</error>
<query xmlns="unknown:ns"/>
</iq>
```
Fixes #66
=> Reply with not-implemented error when there is no route for a received iq get / set

error.go, pres_muc.go, pres_muc_test.go
if `int` is `0` it will not be decoded - because you set `omitempty`.
Solution is to set use pointer so that `omitempty` would handle the pointer and not the value.
On this value a value like `0` is allowed.
---
if you do not use it like here programmed, please create tests for it.
=> muc history of zero stanzes are not supported

_examples/xmpp_echo/xmpp_echo.go, _examples/xmpp_jukebox/xmpp_jukebox.go, client.go, config.go, session.go, stream_logger.go
- Rename socketProxy to StreamLogger
- Ensure client send traffic through the logger
Fixes #76
=> Fix XMPP logger consistency

README.md, _examples/xmpp_echo/xmpp_echo.go, cert_checker.go, config.go, session.go, stanza/starttls.go, stream_manager.go
- You can now pass you own `tls.Config` in config option to override all TLS behaviour. This makes it possible to use the option `InsecureSkipVerify`
- Better logging / reporting on TLS connection errors 
Fixes #88
=> Add support for self-signed certificates

session.go
fix error on implement #90 :
```
Jul 16 00:07:41 apus hook2xmpp[7229]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 16 00:07:41 apus hook2xmpp[7229]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x77a0e4]
Jul 16 00:07:41 apus hook2xmpp[7229]: goroutine 24 [running]:
Jul 16 00:07:41 apus hook2xmpp[7229]: gosrc.io/xmpp.(*Session).startTlsIfSupported(0xc000137d40, 0xd2e6c0, 0xc000010bc0, 0xc00009a48a, 0xc, 0xc0000a0280, 0x11, 0xc00009a480, 0x20, 0xc0002a00c0, ...)
Jul 16 00:07:41 apus hook2xmpp[7229]:         /go/src/gosrc.io/xmpp/session.go:120 +0x274
Jul 16 00:07:41 apus hook2xmpp[7229]: gosrc.io/xmpp.NewSession(0xd2e6c0, 0xc000010bc0, 0xc0000a0280, 0x11, 0xc00009a480, 0x20, 0xc0002a00c0, 0xc0000a02c0, 0x10, 0x0, ...)
Jul 16 00:07:41 apus …
```
=> init empty TLSConfig, if nothing given

client.go
It is the first step - here is no fallback if first srv dns entry not work.
---
fixes #37
=> first implementation with SRV-DNS

client.go, component.go, session.go, stanza/iq.go, stanza/parser.go, stanza/stream_management.go, stream_manager.go
For now it support enabling SM, replying to ack requests from server, and trying resuming the session with existing Stream Management state.
First step in having full support for #47
=> Add initial support for stream management

_examples/go.sum, cmd/go.sum, go.mod, go.sum, stanza/error_test.go, stanza/iot_test.go, stanza/iq.go, stanza/node.go, stanza/node_test.go
It fixes #110, but the things to note, is still that the best approach is to create custom payload structs to support custom XMPP stanza. This is already properly described in `stanza` package documentation: https://github.com/FluuxIO/go-xmpp/blob/master/stanza/README.md#adding-your-own-custom-extensions-on-stanzas
See #110 & #111
=> Generic node should use cdata instead of innerxml

websocket_transport.go, xmpp_transport.go
Since a `Transport` (and a `streamlogger`) does not implement `io.ByteReader`, `xml.Decoder` wraps it using `bufio.NewReader(transport)` so it can easily read bytes one at a time. This has the unfortunate effect of resulting in a panic if we try to parse a stanza that is larger than the default buffer size of 4096 bytes.
To fix this we wrap the transport using `bufio.NewReaderSize()` with a much larger buffer size.
Before the transport work this bug was already present as far as I can see, but only if you enabled logging.
=> Increase size of XML decoder internal buffers

client.go, component.go, go.mod, go.sum, router.go, router_test.go, stanza/iq.go, stanza/iq_test.go, stream_manager.go
This is an attempt to fix #78. The approach I am taking is to introduce an API like this to the router:
```go
router.NewIqResultRoute(context.Background(), "9128171").HandlerFunc(func (s Sender, p stanza.Packet) {
// Process IQ result 
})
```
The context is there to support cancellation and timeouts. They have become a pretty standard feature in golang webservers, and work well here. With a timeout the example becomes:
```go
router.NewIqResultRoute(context.WithTimeout(time.Second * 30, context.Background()), "9128171")
.HandlerFunc(func (s Sender, p stanza.Packet) {
// Process IQ result 
})
.TimeoutHandlerFunc(func (err error) {
// Handle a timeout
})
```
To make this a little easier to use I am thinking of adding a method to `Client` to combine sending an IQ and adding a result route. …
=> IQ result routes

component.go, component_test.go, stanza/parser.go, websocket_transport.go, xmpp_transport.go
In the current code, the decoder is never initialized. The decoder seems to have been "moved to the Transport interface", therefore is does not seem necessary to keep it in the Component struct.  
Also, removing it should prevent usage without initialization.
=> SIGSEGV in xmpp_component example with Prosody #126

README.md, codecov.yml, codeship-services.yml, codeship-steps.yml, codeship.env.encrypted
Removing codecov and codeship as we now use coveralls and github actions
=> Removed codeship and codecov. We now use github actions and coveralls.

client.go, client_test.go
The EventManager methods did not use a pointer as receiver, which caused updates of CurrentState to be lost.
=> Fix updating of EventManager.CurrentState

README.md
As is apparent from the current go.mod file, this library definitely depends on various other libraries.
This in turn makes it depend on Go 1.13 (currently).
=> Remove "no depdencies" statement from README

client.go
=> Close keepalive when recv() ends in client.go

stanza/commands.go, stanza/pubsub_owner.go
Seems like the implementation author just copied the unmarshaller from `stanza/pubsub_owner.go` and forgot to change all the strings and to test if they actually work.
=> Fix marshalling/unmarshalling of command children
