- auth.go
- client.go
- client_test.go
- cmd/xmpp_component/xmpp_component.go
- cmd/xmpp_echo/xmpp_echo.go
- cmd/xmpp_jukebox/xmpp_jukebox.go
- component.go
- component_test.go
- iq.go
- iq_test.go
- message.go
- ns.go
- packet.go
- parser.go
- pep/user_tune.go
- presence.go
- session.go
- stream.go
I also refactored parsing to improve typing (at the expense or more verbose code).
> Add initial support for XMPP components

- component.go
Does somebody tests the component example ?
> [BUGFIX] no pointer in type case in component

- message.go
- pres_muc.go
- pres_muc_test.go
- presence.go
- registry.go
> Implement MUC Presence Extension

- msg_html.go
- msg_html_test.go
> Initial HTML message support

- client.go
- network.go
- network_test.go
> fix connection to ipv6 address + use fallback to jid domain

- component.go
- component_test.go
> stream management for component

- router.go
> Expose Route.AddMatcher

- component.go
> quick fix for component

- _examples/go.sum
- client.go
- client_internal_test.go
- cmd/go.sum
- go.mod
- go.sum
> Fixes issue with unescaped character %

- _examples/xmpp_component/xmpp_component.go
- _examples/xmpp_jukebox/xmpp_jukebox.go
- auth.go
- cert_checker.go
- client.go
- component.go
- component_test.go
- network.go
- network_test.go
- router_test.go
- stanza/component.go
- stanza/error.go
- stanza/iq.go
- stanza/iq_test.go
- stanza/node.go
- stanza/packet_enum.go
- stanza/sasl_auth.go
- stanza/stream.go
- stanza/stream_features.go
- stream_manager.go
- test.sh
Fixed some code style things (changed some hardcoded values to their "const" counterparts for example) and added some tests.
> Tests for Component and code style fixes

- .github/workflows/test.yaml
I noticed you had to fix a failing test after my last PR, which is something I should have noticed myself. To help with that this PR adds a GitHub Action to automatically run all tests.
To enable this you need to [signup for GitHub Actions](https://github.com/features/actions/signup) for the FluuxIO organisation first. After that I should work automatically.
> Setup GitHub actions to run tests

- client.go
- config.go
> Make keepalive interval configurable

- _examples/xmpp_chat_client/config.yml
- _examples/xmpp_chat_client/go.mod
- _examples/xmpp_chat_client/interface.go
- _examples/xmpp_chat_client/xmpp_chat_client.go
- cmd/go.mod
- go.mod
Edited the an example client and made it a TUI client, using :
https://github.com/awesome-gocui/gocui
> Basic terminal client

- _examples/xmpp_chat_client/go.mod
- _examples/xmpp_chat_client/interface.go
- _examples/xmpp_chat_client/xmpp_chat_client.go
Added roster update to chat client example
> Added roster update to chat client example

- _examples/xmpp_chat_client/README.md
- _examples/xmpp_chat_client/config.yml
- _examples/xmpp_chat_client/interface.go
- _examples/xmpp_chat_client/xmpp_chat_client.go
- client.go
- client_test.go
- component.go
- stanza/parser.go
- stanza/stream_features.go
- stream_manager.go
- transport.go
- websocket_transport.go
- xmpp_transport.go
Added the ability for the parser to register </stream:stream> tags.
Also updated example with a README.md and fixed some logs.
> Changed "Disconnect" to wait for the closing stream tag.

- _examples/xmpp_pubsub_client/xmpp_ps_client.go
A short and simple PubSub example.  
In it, we : 
- Create a client
- Make it create a node on a service
- Subscribe to that node
- Publish to that node
- Print the notification coming from the publish action
> PubSub example

- _examples/xmpp_pubsub_client/xmpp_ps_client.go
- stanza/form.go
- stanza/form_test.go
- stanza/pubsub_owner.go
- stanza/pubsub_owner_test.go
- stanza/pubsub_test.go
Cleaned up the code.  
Changed from []Field to []*Field in Form which seems easier to manage.  
Added NewFormSubmissionOwner to the Owner namespace for pubsubs and tests for it.
> Pub sub example update

- cmd/go.sum
- go.mod
Removed unnecessary dependencies from the core lib go.mod
> Removed unnecessary dependencies from the core lib go.mod

- xmpp_transport.go
> Reset isSecure in StartTLS()

- client.go
- stream_manager.go
> Fix issue #160

- go.sum
- stanza/msg_hint.go
- stanza/msg_hint_test.go
Support for XEP-0334 (Message Hints), needed for XEP-0313 (MAM)
> Support for XEP-0334Support for XEP-0334 (Message Hints)

- stanza/datetime_profiles.go
- stanza/datetime_profiles_test.go
Parsing of times with an offset does not work for now (should it ?)
> WIP: Support for XEP-0082.
